/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorIndexRouteImport } from './routes/tutor/index'
import { Route as ExamModeIndexRouteImport } from './routes/exam-mode/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as QuickExercisesExerciseSlugRouteImport } from './routes/quick-exercises/$exerciseSlug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as ExamModeResultsIndexRouteImport } from './routes/exam-mode/results/index'

const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamModeIndexRoute = ExamModeIndexRouteImport.update({
  id: '/exam-mode/',
  path: '/exam-mode/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickExercisesExerciseSlugRoute =
  QuickExercisesExerciseSlugRouteImport.update({
    id: '/quick-exercises/$exerciseSlug',
    path: '/quick-exercises/$exerciseSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamModeResultsIndexRoute = ExamModeResultsIndexRouteImport.update({
  id: '/exam-mode/results/',
  path: '/exam-mode/results/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/quick-exercises/$exerciseSlug': typeof QuickExercisesExerciseSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/exam-mode': typeof ExamModeIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/exam-mode/results': typeof ExamModeResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/quick-exercises/$exerciseSlug': typeof QuickExercisesExerciseSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/exam-mode': typeof ExamModeIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/exam-mode/results': typeof ExamModeResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/quick-exercises/$exerciseSlug': typeof QuickExercisesExerciseSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/exam-mode/': typeof ExamModeIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/exam-mode/results/': typeof ExamModeResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/new'
    | '/notifications'
    | '/text-to-speech'
    | '/courses/$courseId'
    | '/demo/tanstack-query'
    | '/quick-exercises/$exerciseSlug'
    | '/courses'
    | '/exam-mode'
    | '/tutor'
    | '/exam-mode/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/new'
    | '/notifications'
    | '/text-to-speech'
    | '/courses/$courseId'
    | '/demo/tanstack-query'
    | '/quick-exercises/$exerciseSlug'
    | '/courses'
    | '/exam-mode'
    | '/tutor'
    | '/exam-mode/results'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new'
    | '/notifications'
    | '/text-to-speech'
    | '/courses/$courseId'
    | '/demo/tanstack-query'
    | '/quick-exercises/$exerciseSlug'
    | '/courses/'
    | '/exam-mode/'
    | '/tutor/'
    | '/exam-mode/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  QuickExercisesExerciseSlugRoute: typeof QuickExercisesExerciseSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ExamModeIndexRoute: typeof ExamModeIndexRoute
  TutorIndexRoute: typeof TutorIndexRoute
  ExamModeResultsIndexRoute: typeof ExamModeResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-mode/': {
      id: '/exam-mode/'
      path: '/exam-mode'
      fullPath: '/exam-mode'
      preLoaderRoute: typeof ExamModeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-exercises/$exerciseSlug': {
      id: '/quick-exercises/$exerciseSlug'
      path: '/quick-exercises/$exerciseSlug'
      fullPath: '/quick-exercises/$exerciseSlug'
      preLoaderRoute: typeof QuickExercisesExerciseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-mode/results/': {
      id: '/exam-mode/results/'
      path: '/exam-mode/results'
      fullPath: '/exam-mode/results'
      preLoaderRoute: typeof ExamModeResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  QuickExercisesExerciseSlugRoute: QuickExercisesExerciseSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ExamModeIndexRoute: ExamModeIndexRoute,
  TutorIndexRoute: TutorIndexRoute,
  ExamModeResultsIndexRoute: ExamModeResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
